"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.isEmpty = exports.isRichObj = exports.isEmptyObj = exports.isObj = void 0;
const isObj = (o) => typeof o === 'function' || (o !== null && typeof o === 'object');
exports.isObj = isObj;
const isEmptyObj = (o) => Reflect.ownKeys(o).length === 0;
exports.isEmptyObj = isEmptyObj;
const isRichObj = (o) => Reflect.ownKeys(o).length > 0;
exports.isRichObj = isRichObj;
const isEmpty = v => v === undefined || v === null || v === NaN;
exports.isEmpty = isEmpty;
